using System.Collections.Generic;

namespace AdvancedPS.Core
{
    /// <summary>
    /// Query helpers over the generated <see cref="Entries"/> catalog — the hand-written half of the partial
    /// (the data half, <c>AddressablePopupIndex.generated.cs</c>, is regenerated by the editor). Core uses these
    /// to decide what to load; a <see cref="System.IPopupResolver"/> turns the chosen addresses into live popups.
    /// </summary>
    internal static partial class AddressablePopupIndex
    {
        /// <summary>
        /// True when at least one popup is flagged Addressable — a cheap gate so the scene-only path pays nothing.
        /// </summary>
        internal static bool HasEntries => Entries.Length > 0;

        /// <summary>
        /// Entries that participate in <paramref name="layer"/> (same <c>HasFlag</c> matching as live popups).
        /// </summary>
        internal static IEnumerable<Entry> ForLayer(PopupLayerEnum layer)
        {
            for (int i = 0; i < Entries.Length; i++)
                if (Entries[i].Layer.HasFlag(layer))
                    yield return Entries[i];
        }

        /// <summary>
        /// Entries whose <see cref="LoadMode"/> is <see cref="LoadMode.Preload"/> — loaded by the boot preload pass.
        /// </summary>
        internal static IEnumerable<Entry> Preloads
        {
            get
            {
                for (int i = 0; i < Entries.Length; i++)
                    if (Entries[i].LoadMode == LoadMode.Preload)
                        yield return Entries[i];
            }
        }

        /// <summary>
        /// Finds the entry for a popup type by its <c>Type.FullName</c>. Used by the by-type show/spawn paths.
        /// </summary>
        internal static bool TryGetByTypeName(string typeName, out Entry entry)
        {
            for (int i = 0; i < Entries.Length; i++)
            {
                if (Entries[i].TypeName == typeName)
                {
                    entry = Entries[i];
                    return true;
                }
            }
            entry = default;
            return false;
        }
    }
}
