using System;
using UnityEngine;

namespace AdvancedPS.Core
{
    /// <summary>
    /// The Addressable popup catalog as data — the runtime half of the index. One <see cref="Entry"/> per
    /// Addressable-flagged popup (its Addressables key + load / scene-preload settings), regenerated by the editor
    /// (<c>AddressablePopupIndexGenerator</c>) from a prefab scan and queried through <see cref="AddressablePopupIndex"/>.
    /// <para>
    /// Replaces the former generated <c>AddressablePopupIndex.generated.cs</c>: writing an <b>asset</b> instead of C#
    /// means flagging a popup Addressable no longer recompiles scripts or reloads the domain. The single asset lives in
    /// the consumer's <c>Assets/Resources/APS_AddressablePopupIndex.asset</c> — <b>outside</b> the package, so a
    /// <c>.unitypackage</c> update never clobbers it and it is never shipped (the same rule as <c>AP_Settings.json</c> /
    /// <see cref="LayerCanvasConfig"/>). A missing asset simply means an empty catalog (the scene-only fast path).
    /// </para>
    /// </summary>
    public class AddressablePopupIndexAsset : ScriptableObject
    {
        /// <summary> Resources name of the consumer's index asset (loaded lazily by <see cref="Loaded"/>). </summary>
        public const string ResourceName = "APS_AddressablePopupIndex";

        /// <summary>
        /// One Addressable popup: how to load it and where it belongs. <see cref="TypeName"/> is the popup component's
        /// <c>Type.FullName</c> — matched against live popups for the scene-wins dedup. <see cref="PreloadScenePaths"/> /
        /// <see cref="UnloadScenePaths"/> are scene asset paths baked from the popup's stored scene GUIDs so the runtime
        /// matches <c>scene.path</c> without touching Addressables / the AssetDatabase. An <b>empty</b>
        /// <see cref="PreloadScenePaths"/> means "preload in every scene" (the default); an empty
        /// <see cref="UnloadScenePaths"/> means "never unload".
        /// </summary>
        [Serializable]
        public class Entry
        {
            public string TypeName;
            public string Address;
            public PopupLayerEnum Layer;
            public LoadMode LoadMode;
            public string[] PreloadScenePaths = Array.Empty<string>();
            public string[] UnloadScenePaths = Array.Empty<string>();
        }

        [Tooltip("One entry per Addressable-flagged popup. Regenerated by the APS Addressable index tooling — do not hand-edit.")]
        public Entry[] Entries = Array.Empty<Entry>();

        #region Loaded
        private static AddressablePopupIndexAsset _loaded;
        private static bool _loadedResolved;

        /// <summary>
        /// The consumer's index asset, loaded once from Resources ("<see cref="ResourceName"/>") and cached. Null when
        /// no asset exists yet (no Addressable popups / a fresh project) — then the catalog is empty and the system
        /// stays on the scene-only path.
        /// </summary>
        public static AddressablePopupIndexAsset Loaded
        {
            get
            {
                if (!_loadedResolved)
                {
                    _loaded = Resources.Load<AddressablePopupIndexAsset>(ResourceName);
                    _loadedResolved = true;
                }
                return _loaded;
            }
        }

        /// <summary> Drops the cached asset so it is reloaded on next use. Called on play-mode exit (leak guard). </summary>
        internal static void ClearCache()
        {
            _loaded = null;
            _loadedResolved = false;
        }
        #endregion
    }
}
