using System;
using System.Collections.Generic;
using Entry = AdvancedPS.Core.AddressablePopupIndexAsset.Entry;

namespace AdvancedPS.Core
{
    /// <summary>
    /// Query helpers over the Addressable popup catalog. The data lives in <see cref="AddressablePopupIndexAsset"/>
    /// (a ScriptableObject in the consumer's Resources, regenerated by the editor); this is the hand-written query
    /// half. Core uses these to decide what to load; a <see cref="System.IPopupResolver"/> turns the chosen addresses
    /// into live popups. A missing asset → empty catalog (the scene-only fast path).
    /// </summary>
    internal static class AddressablePopupIndex
    {
        /// <summary> The current catalog entries, or empty when no index asset exists. </summary>
        private static Entry[] Entries =>
            AddressablePopupIndexAsset.Loaded != null ? AddressablePopupIndexAsset.Loaded.Entries : Array.Empty<Entry>();

        /// <summary>
        /// True when at least one popup is flagged Addressable — a cheap gate so the scene-only path pays nothing.
        /// </summary>
        internal static bool HasEntries => Entries.Length > 0;

        /// <summary>
        /// Entries whose layer is in <paramref name="layer"/> — a single flag, or a mask to match any of several
        /// layers (same any-of matching as live popups).
        /// </summary>
        internal static IEnumerable<Entry> ForLayer(PopupLayerEnum layer)
        {
            Entry[] entries = Entries;
            for (int i = 0; i < entries.Length; i++)
                if ((entries[i].Layer & layer) != 0)
                    yield return entries[i];
        }

        /// <summary>
        /// Entries whose <see cref="LoadMode"/> is <see cref="LoadMode.Preload"/> — loaded by the boot preload pass.
        /// </summary>
        internal static IEnumerable<Entry> Preloads
        {
            get
            {
                Entry[] entries = Entries;
                for (int i = 0; i < entries.Length; i++)
                    if (entries[i].LoadMode == LoadMode.Preload)
                        yield return entries[i];
            }
        }

        /// <summary>
        /// Preload-mode entries that want <paramref name="scenePath"/> preloaded — an <b>empty</b>
        /// <see cref="AddressablePopupIndexAsset.Entry.PreloadScenePaths"/> means "every scene" (the Everyone default);
        /// otherwise only when the path is listed (the baked scene GUIDs). Eagerly loaded by the per-scene pass.
        /// </summary>
        internal static IEnumerable<Entry> PreloadsForScene(string scenePath)
        {
            Entry[] entries = Entries;
            for (int i = 0; i < entries.Length; i++)
            {
                if (entries[i].LoadMode != LoadMode.Preload) continue;
                string[] paths = entries[i].PreloadScenePaths;
                if (paths == null || paths.Length == 0 || ContainsPath(paths, scenePath))
                    yield return entries[i];
            }
        }

        /// <summary>
        /// Entries whose <see cref="AddressablePopupIndexAsset.Entry.UnloadScenePaths"/> contains
        /// <paramref name="scenePath"/> — released from memory by the per-scene pass when that scene loads.
        /// </summary>
        internal static IEnumerable<Entry> UnloadsForScene(string scenePath)
        {
            Entry[] entries = Entries;
            for (int i = 0; i < entries.Length; i++)
                if (ContainsPath(entries[i].UnloadScenePaths, scenePath))
                    yield return entries[i];
        }

        private static bool ContainsPath(string[] paths, string scenePath)
        {
            if (paths == null) return false;
            for (int i = 0; i < paths.Length; i++)
                if (paths[i] == scenePath)
                    return true;
            return false;
        }

        /// <summary>
        /// Finds the entry for a popup type by its <c>Type.FullName</c>. Used by the by-type show/spawn paths.
        /// </summary>
        internal static bool TryGetByTypeName(string typeName, out Entry entry)
        {
            Entry[] entries = Entries;
            for (int i = 0; i < entries.Length; i++)
            {
                if (entries[i].TypeName == typeName)
                {
                    entry = entries[i];
                    return true;
                }
            }
            entry = default;
            return false;
        }
    }
}
