using System;
using System.IO;
using AdvancedPS.Core.System;
using Newtonsoft.Json;
using UnityEngine;

namespace AdvancedPS.Core.Utils
{
    public static class FileSearcher
    {
        private const string PackageFolderName = "advanced-popup-system";
        
        private const string DisplaysPath = "Runtime/Generated/Displays/";
        private const string LayersEnumPath = "Runtime/Generated/";
        private const string ImagesPath = "Runtime/Images/";

        private const string LayersEnumFileName = "PopupLayerEnum.generated.cs";
        private const string AddressableIndexFileName = "AddressablePopupIndex.generated.cs";

        // Minimal, COMPILABLE defaults used only as a safety net when a generated file is missing (a corrupted or
        // partial import). Writing an empty file here would leave the project without the PopupLayerEnum type or the
        // AddressablePopupIndex.Entries array — a hard compile error. The editor tooling regenerates the real content
        // (layers from the external store, the index from a prefab scan) right after.
        private const string DefaultLayersEnumContent =
            "using System;\n" +
            "namespace AdvancedPS.Core\n" +
            "{\n" +
            "    [Flags]\n" +
            "    public enum PopupLayerEnum\n" +
            "    {\n" +
            "        None = 0,\n" +
            "    }\n" +
            "}\n";

        private const string DefaultAddressableIndexContent =
            "using System;\n" +
            "namespace AdvancedPS.Core\n" +
            "{\n" +
            "    internal static partial class AddressablePopupIndex\n" +
            "    {\n" +
            "        internal readonly struct Entry\n" +
            "        {\n" +
            "            public readonly string TypeName;\n" +
            "            public readonly string Address;\n" +
            "            public readonly PopupLayerEnum Layer;\n" +
            "            public readonly LoadMode LoadMode;\n" +
            "            public readonly HideBehavior HideBehavior;\n" +
            "            public Entry(string typeName, string address, PopupLayerEnum layer, LoadMode loadMode, HideBehavior hideBehavior)\n" +
            "            {\n" +
            "                TypeName = typeName; Address = address; Layer = layer; LoadMode = loadMode; HideBehavior = hideBehavior;\n" +
            "            }\n" +
            "        }\n" +
            "        internal static readonly Entry[] Entries = Array.Empty<Entry>();\n" +
            "    }\n" +
            "}\n";

        public static readonly string ImagesFolderPath;
        public static readonly string DisplaysFolderPath;
        public static readonly string LayersEnumFilePath;
        /// <summary>Full path of the generated Addressable popup index (Runtime/Generated/). Regenerated by the editor.</summary>
        public static readonly string AddressableIndexFilePath;

        static FileSearcher()
        {
            ImagesFolderPath = GetImagesFolderPathInternal().Replace(@"\", "/");
            DisplaysFolderPath = GetDisplaysFolderPathInternal().Replace(@"\", "/");
            LayersEnumFilePath = GetLayersEnumFilePathInternal().Replace(@"\", "/");
            AddressableIndexFilePath = GetGeneratedFilePathInternal(AddressableIndexFileName).Replace(@"\", "/");
        }
        
        public static string ToAssetPath(string pathFs)
        {
            var p = pathFs.Replace("\\", "/");
            if (p.StartsWith("Assets/") || p == "Assets") return p;

            var data = Application.dataPath.Replace("\\", "/");
            if (!p.StartsWith(data))
                throw new Exception($"Path not under Assets: {p}");

            return "Assets" + p.Substring(data.Length);
        }

        public static string ToFsPath(string assetPath)
        {
            var p = assetPath.Replace("\\", "/");
            if (!p.StartsWith("Assets"))
                throw new Exception($"Not an asset path: {p}");
            return Path.Combine(Application.dataPath, p.Substring("Assets".Length)).Replace("\\", "/");
        }

        
        private static string GetImagesFolderPathInternal()
        {
            string folderPath = FindProtectedFolderPath();
            if (string.IsNullOrEmpty(folderPath))
            {
                throw new DirectoryNotFoundException($"The folder '{PackageFolderName}' was not found.");
            }

            string imagesFolderPath = Path.Combine(folderPath, ImagesPath);
            if (!Directory.Exists(imagesFolderPath))
            {
                Directory.CreateDirectory(imagesFolderPath);
            }

            return imagesFolderPath;
        }
        
        private static string GetDisplaysFolderPathInternal()
        {
            string folderPath = FindProtectedFolderPath();
            if (string.IsNullOrEmpty(folderPath))
            {
                throw new DirectoryNotFoundException($"The folder '{PackageFolderName}' was not found.");
            }

            string imagesFolderPath = Path.Combine(folderPath, DisplaysPath);
            if (!Directory.Exists(imagesFolderPath))
            {
                Directory.CreateDirectory(imagesFolderPath);
            }

            return imagesFolderPath;
        }
        
        private static string GetLayersEnumFilePathInternal()
        {
            string folderPath = FindProtectedFolderPath();
            if (string.IsNullOrEmpty(folderPath))
            {
                throw new DirectoryNotFoundException($"The folder '{PackageFolderName}' was not found.");
            }

            string layersEnumFolderPath = Path.Combine(folderPath, LayersEnumPath);
            if (!Directory.Exists(layersEnumFolderPath))
            {
                Directory.CreateDirectory(layersEnumFolderPath);
            }
            
            string settingsFilePath = Path.Combine(layersEnumFolderPath, LayersEnumFileName);
            if (!File.Exists(settingsFilePath))
            {
#if UNITY_EDITOR
                // Seed a compilable default (never an empty file — that removes the PopupLayerEnum type).
                File.WriteAllText(settingsFilePath, DefaultLayersEnumContent);
#endif
            }

            return settingsFilePath;
        }

        /// <summary>
        /// Full path of a generated file in Runtime/Generated/ by file name (creates the folder, and an empty
        /// placeholder if missing). Used for the Addressable popup index.
        /// </summary>
        private static string GetGeneratedFilePathInternal(string fileName)
        {
            string folderPath = FindProtectedFolderPath();
            if (string.IsNullOrEmpty(folderPath))
            {
                throw new DirectoryNotFoundException($"The folder '{PackageFolderName}' was not found.");
            }

            string generatedFolderPath = Path.Combine(folderPath, LayersEnumPath);
            if (!Directory.Exists(generatedFolderPath))
            {
                Directory.CreateDirectory(generatedFolderPath);
            }

            string filePath = Path.Combine(generatedFolderPath, fileName);
            if (!File.Exists(filePath))
            {
#if UNITY_EDITOR
                // Seed compilable default content (never an empty file — the hand-written partial reads Entries).
                File.WriteAllText(filePath,
                    fileName == AddressableIndexFileName ? DefaultAddressableIndexContent : string.Empty);
#endif
            }

            return filePath;
        }

        private static string FindProtectedFolderPath()
        {
#if UNITY_EDITOR
            string[] guids = UnityEditor.AssetDatabase.FindAssets("t:Folder " + PackageFolderName);
            foreach (string guid in guids)
            {
                string path = UnityEditor.AssetDatabase.GUIDToAssetPath(guid);
                if (Path.GetFileName(path) == PackageFolderName)
                {
                    return path;
                }
            }
            return null;
#else
            string path = Path.Combine(UnityEngine.Application.dataPath, PackageFolderName);
            if (Directory.Exists(path))
            {
                return path;
            }
            return null;
#endif
        }
        
        private static void GenerateBaseSettingsFile(string path)
        {
            var baseSettings = new PopupSettings
            {
                InspectorView = InspectorEnum.APSInspector,
                LogType = "Error"
            };

            File.WriteAllText(path, JsonConvert.SerializeObject(baseSettings));
#if UNITY_EDITOR
            UnityEditor.AssetDatabase.Refresh();
#endif
        }
    }
}